spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 15s
        instance-id: pcus-movie
  application:
    name: pcus-movie
server:
  port: 9093