spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 15s
        instance-id: pcus-report
  application:
    name: pcus-report
  datasource:
      url: jdbc:oracle:thin:@//192.168.0.221:1521/ORCL
      username: TMSDEV
      password: TMSDEV
      driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org.apache.ibatis: DEBUG

# ureport Oracle 存储
ureport.oracle.provider:
  prefix: oracle-
  disabled: false
  fileStoreDir: E:/UReportFile

server:
  port: 9180
  address: localhost