spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${server.context-path}/health
        health-check-interval: 15s
        instance-id: pcus-gateway
  application:
    name: pcus-gateway

server:
  port: 9090
  context-path: /pcus
zuul:
  debug:
    request: true
  strip-prefix: false
  routes:
    pcus-module-core:
      path: /core/**
      service-id: pcus-module-core
    pcus-movie:
      path: /movie/**
      service-id: pcus-movie
logging:
  level:
    com.netflix: DEBUG
