spring:
  application:
    name: pcus-gateway #应用名称，会显示在consul服务发现
  session:
    store-type: redis
server:
  port: 9090
  context-path: /pcus
#  tomcat:
#    basedir: pcusdata
security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:9090/pcus/auth/oauth/token
#      user-authorization-uri: http://localhost:9090/pcus/auth/oauth/authorize
#      client-id: webapp
#    resource:
#      user-info-uri: http://localhost:9090/pcus/auth/user
#      prefer-token-info: false
  basic:
    enabled: false
zuul: #路由配置
  sensitive-headers:  #不过滤header，完整发送header到子服务
  debug:
    request: true       #请求日志
  strip-prefix: false
  routes:               #路由规则，service-id就子服务的application name
    pcus-module-core:
      path: /core/**
      service-id: pcus-module-core
    pcus-auth:
      path: /auth/**
      service-id: pcus-auth
    pcus-report:       #报表服务
      path: /report/**
      service-id: pcus_report
feign: #注解式http客户端
  hystrix:  #断路器，当调用后端服务失败时的保护措施
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

