spring:
  devtools:
    livereload:
      enabled: true
    restart:
      additional-exclude: values/** #设置values目录不重启，因为这个工具只是默认了static和templates等是不重启的
  cloud:
    consul: #服务发现配置
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${server.context-path}/health #健康检测url
        health-check-interval: 100s
        instance-id: pcus-gateway
  redis: #redis连接配置
    host: 192.168.0.221
    pool:
      max-active: 8
      max-idle: 0
      max-wait: -1
ribbon:
  ReadTimeout: 360000  #读取超时时间6分钟
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500
server:
  tomcat:
    max-threads: 10
