spring:
  devtools:
    livereload:
      enabled: true
  redis:
    host: 192.168.0.221
    pool:
      max-active: 8
      max-idle: 0
      max-wait: -1
logging:
  level:
#    com.netflix: debug
#    org.springframework.security: debug
    org.springframework.session: debug
security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:9090/pcus/auth/oauth/token
#      user-authorization-uri: http://localhost:9090/pcus/auth/oauth/authorize
#      client-id: webapp
#    resource:
#      user-info-uri: http://localhost:9090/pcus/auth/user
#      prefer-token-info: false
  basic:
    enabled: false


