spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 15s
        instance-id: pcus-module-core
  application:
    name: pcus-module-core
server:
  port: 9091