spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 15s
        instance-id: pcus-job
  application:
    name: pcus-job
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.217:1521:orcl
    username: pcusdev
    password: pcusdev
    druid:
      max-active: 10
      min-idle: 2
      initial-size: 5
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 3000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 'x' FROM DUAL
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        slf4j:
          statement-sql-pretty-format: true
          result-set-log-enabled: false
          statement-executable-sql-log-enable: false
          enabled: true

logging:
  level:
    org.apache.ibatis: DEBUG
xxl:
  job:
    admin:
      addresses: http://192.168.0.217:9096/xxl-job-admin
    executor:
      appname: pcus-job-executor
      ip:
      port: 9999
      logpath: /schedule/pcus-job/jobhandler
      logretentiondays: -1
    accessToken:
