spring:
  devtools:
    livereload:
      enabled: true
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.0.221

    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 10
      # 连接池中的最大空闲连接
      max-idle: 4
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
  datasource:
#    hikari:
#      username: pcusdev
#      password: pcusdev
#      minimum-idle: 5
#      maximum-pool-size: 10
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: PcusDS
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1 FROM DUEL
#      jdbc-url: jdbc:oracle:thin:@192.168.0.221:1521:orcl
#      driver-class-name: oracle.jdbc.OracleDriver
#    type: com.zaxxer.hikari.HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: pcusdev
    password: pcusdev
#    minimum-idle: 5
#    maximum-pool-size: 10
#    auto-commit: true
#    idle-timeout: 30000
#    pool-name: PcusDS
#    max-lifetime: 1800000
#    connection-timeout: 30000
#    connection-test-query: SELECT 1 FROM DUEL
#    jdbc-url: jdbc:oracle:thin:@192.168.0.221:1521:orcl
    filters: stat,wall,log4j
    url: jdbc:oracle:thin:@192.168.0.217:1521:orcl
logging:
  level:
#    com.netflix: debug
#    org.springframework.security: debug
#    org.springframework.session: debug
security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:9090/pcus/auth/oauth/token
#      user-authorization-uri: http://localhost:9090/pcus/auth/oauth/authorize
#      client-id: webapp
#    resource:
#      user-info-uri: http://localhost:9090/pcus/auth/user
#      prefer-token-info: false
  basic:
    enabled: false


